name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.ARTIFACTORY_URL }}
    - name: Build
      run: docker build -t back .
    - name: Tags
      run: |
          docker tag back ${{ secrets.DOCKER_USER }}/back:latest
    - name: Push
      run: |
          docker push ${{ secrets.DOCKER_USER }}/back:latest
      

